### ISSUE TITLE
Can't yarn install the repository

### ISSUE THREAD

**Issue by haithai91** [kobee-tech-stack/aws-development-with-localstack#3]
error An unexpected error occurred: "https://registry.yarnpkg.com/@aws-cdk%2faws-dynamodb: self signed certificate in certificate chain".
info If you think this is a bug, please open a bug report with the information provided in "/Users/haithai/workspace/tools/aws-development-with-localstack/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by pub-technology** [comment]
try to run this command `yarn config set "strict-ssl" false` and execute `yarn install`
